In [11]:
import numpy as np


def multiply(n):
    num2=list(range(n))
    num1=list(range(1,5*n,5))
    mul=[]
    for i in range(len(num1)):
        mul.append(num2[i]**2+num1[i]**3)
    return mul
print(multiply(10))


# 等价于
def pynum(n):
    num2=np.arange(n)
    num1=np.arange(1,5*n,5)
    mul=num2**2+num1**3
    return mul
print(pynum(10))


[1, 217, 1335, 4105, 9277, 17601, 29827, 46705, 68985, 97417]
[    1   217  1335  4105  9277 17601 29827 46705 68985 97417]


In [1]:
import datetime

dt=datetime.datetime.now()
print(dt)

2021-07-07 20:04:47.303590


In [4]:
import numpy as np
a=np.float64(23)
print('整数转化为64位浮点数',a)

c=np.bool(2)
print(c)

整数转化为64位浮点数 23.0
True


并不是所有的NumPy数据类型都可以直接进行转换。例如复数数据类型不能转换成其他类型。

通过dtype参数值显示控制生成数据的数据类型

In [7]:
a=np.arange(3,dtype=np.float32)
print(a)
print(type(a[0]))

[0. 1. 2.]
<class 'numpy.float32'>


最常用的是使用array方法从常规的Python列表或元组直接创造数组


In [11]:
a=np.array([2,3,4])
print(a)
print(type(a))
print(a.dtype)

[2 3 4]
<class 'numpy.ndarray'>
int32


In [14]:
c=np.array([[1,2],[3,4]],dtype=complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [17]:
import numpy as np
x = np.zeros((3, 4))  #创建元素全为0的多维数组
print (x)
y = np.ones( (2, 3, 4), dtype=int)  #创建元素全为1的多维数组
print (y)
z = np.empty((3, 2), dtype = int)  #创建元素全未初始化的多维数组
print (z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1527090704        384]
 [         0          0]
 [   3997795         97]]


In [29]:
a=np.arange(24)
print(a.ndim)
b=a.reshape(2,4,3)
print(b.ndim)

1
3


In [32]:
a=np.arange(10)
print(a)
print(a[3:6]) # 切片操作

print(a[:7:2]) # 按一定的步数(2步)切片

[0 1 2 3 4 5 6 7 8 9]
[3 4 5]
[0 2 4 6]


In [39]:
a=np.arange(6)
print(a)
b=np.arange(12).reshape(3,4)
print("b=",b)
c=np.arange(24).reshape(2,3,4)
print("c=",c)

[0 1 2 3 4 5]
b= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
c= [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [45]:
a=np.floor(10*np.random.random((3,4)))
print(a)
print(a.shape)

[[8. 0. 8. 3.]
 [1. 6. 4. 9.]
 [2. 0. 7. 7.]]
(3, 4)


In [54]:
a=np.floor(10*np.random.random((3,4)))
print(a)
b=a.ravel()
print(b.shape) # 转成一维数组
print("b=",b)

print(a.reshape(6,2))
print(a.T) # 转置

[[9. 1. 4. 8.]
 [7. 0. 7. 0.]
 [4. 3. 6. 8.]]
(12,)
b= [9. 1. 4. 8. 7. 0. 7. 0. 4. 3. 6. 8.]
[[9. 1.]
 [4. 8.]
 [7. 0.]
 [7. 0.]
 [4. 3.]
 [6. 8.]]
[[9. 7. 4.]
 [1. 0. 3.]
 [4. 7. 6.]
 [8. 0. 8.]]


In [61]:
a=np.floor(10*np.random.random((3,4)))
print(a)
a.resize(2,6)
print(a)

[[8. 2. 0. 9.]
 [9. 1. 2. 6.]
 [4. 6. 8. 2.]]
[[8. 2. 0. 9. 9. 1.]
 [2. 6. 4. 6. 8. 2.]]


改变数组形状的任一维度参数为-1时，数组维度会被自动计算。



In [77]:
a=np.floor(10*np.random.random((3,4)))
print(a.reshape(4,-1))

[[9. 0. 2.]
 [1. 6. 1.]
 [5. 8. 4.]
 [4. 6. 8.]]


不同方向的数组组合方法，分别是水平组合、垂直组合、深度组合

In [81]:
a=np.arange(9).reshape(3,3)
b=a*2
print("a=",a)
print("b=",b)
print("水平组合",np.hstack((a,b)))
print("水平组合",np.concatenate((a,b),axis=1))

print("垂直组合",np.vstack((a,b)))
print("垂直组合",np.concatenate((a,b),axis=0))

print("深度组合",np.dstack((a,b)))

a= [[0 1 2]
 [3 4 5]
 [6 7 8]]
b= [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
水平组合 [[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
水平组合 [[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
垂直组合 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
垂直组合 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
深度组合 [[[ 0  0]
  [ 1  2]
  [ 2  4]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]]]


In [83]:
a = np.arange(9).reshape(3, 3)  # 创建一些数组
b = 2 * a
a1=a.reshape(3,3,1)
b1=b.reshape(3,3,1)
print(np.concatenate((a1,b1),axis=2))

[[[ 0  0]
  [ 1  2]
  [ 2  4]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]]]


# NumPy矩阵基础

## 广播机制

In [4]:
import numpy as np
a=np.array(([[ 0.9526, -0.246 , -0.8856],
           [ 0.5639, 0.2379, 0.9104]]))
print(a*10)

[[ 9.526 -2.46  -8.856]
 [ 5.639  2.379  9.104]]


## 矩阵对象
matrix是Ndarray的分支，所以matrix和Ndarray在很多时候都是通用的。

matrix的优势就是相对简单的运算符号，如矩阵相乘用符号*，但是Ndarray相乘得用方法.dot()

In [8]:
A=np.matrix('1 2 3;4 5 6;7 8 9')
print(A)

print(A.T) # A的转置

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
A=np.matrix('1 2 3;4 5 6;7 8 9')+np.random.random((3,3))
print(A)
print(A.I) # A得逆矩阵

[[1.42884535 2.95927132 3.57128946]
 [4.69344932 5.20664037 6.05182638]
 [7.16916443 8.26231695 9.66419025]]
[[ -1.57783658  -4.53668051   3.4239924 ]
 [  9.85025084  58.91885069 -40.53570367]
 [ -7.25090492 -47.00673296  32.21911604]]


# NumPy方法进阶
常用的文件读写和算数运算两种方法。


In [13]:
a=np.arange(0,12)
a=a.reshape(3,4)
print(a)
np.save('a.npy',a)
c=np.load('a.npy')
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


savetxt和loadtxt两个方法专用存取csv文件


In [15]:
a=np.arange(0,12)
a=a.reshape(3,4)
np.savetxt('a.txt',a)
c=np.loadtxt('a.txt')
print(c)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [16]:
a=np.array([[2,7,5],[2,4,3],[2,4,6]])
print("a=",a)
print(np.ptp(a)) # 整个多维数组的最大最小之差
print(np.ptp(a,axis=1)) # 每行的最大最小之差
print(np.ptp(a,axis=0)) # 每列的最大最小之差

a= [[2 7 5]
 [2 4 3]
 [2 4 6]]
5
[5 2 4]
[0 3 3]
